name = "Krippendorff"
uuid = "08378ef3-8d37-44eb-940a-2e19b2c00443"
authors = ["FPGro <38361879+FPGro@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
